# Generated by Django 5.1.2 on 2024-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroceryItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("wholesale_price", models.CharField(max_length=10)),
                ("retail_price", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("entry_date", models.DateTimeField()),
            ],
            options={
                "db_table": "grocery",
            },
        ),
    ]
