# Generated by Django 5.1.2 on 2024-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_groceryitems_entry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("loc", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=40)),
                ("mob", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "store",
            },
        ),
    ]
